#!/usr/bin/ruby -wT1

require "cgi"
require 'uri'
require 'pp'

cgi = CGI.new("html4")  # add HTML generation methods

form = <<EOFORM
  <form action="route" method="get">
    Where are you now? <input type="text" size="40" name="origin" value="Christchurch City Council,Hereford St, Christchurch"><br/>
    Where do you want to go to? <input type="text" size="40" name="destination" value="245 wooldridge road,christchurch">
    <input type="submit" value="Let's Go!"  />
EOFORM

if cgi.params.has_key?( "origin") && cgi.params.has_key?( "destination")
  origin = cgi.params["origin"].join(" ").gsub(%r{[^\.,a-zA-Z0-9\-_ ]}, '').untaint
  destination = cgi.params["destination"].join(" ").gsub(%r{[^\.,a-zA-Z0-9\-_ ]}, '').untaint

  cmd = "cd ../..;./pull_routes '#{origin}' '#{destination}' | ./scan_routes"

  content = `#{cmd}`
  
  puts "\
Content-Type: text/json\r
Content-Length: #{content.size}\r
\r
"
  puts content
  
else
  cgi.out do
    cgi.html do
      cgi.head do
        cgi.title { "TITLE" }
      end +
        cgi.body do
        form
      end
    end
  end
end

